constructor_site/constructor_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('', include('management_site.urls', namespace='management_site')),
    path('figma/', include('figma.urls')),
    path('<str:user_site>/sale/clothes/', include('sale_clothes.urls')),
    path('crm/', include('mini_crm.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

constructor_site/figma/urls.py
from django.urls import path
from . import views

app_name = 'figma'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),
    path('<int:category>',views.ClientIndexView.as_view(), name ='index'),
    path('detail/<int:good>',views.ClientDetailView.as_view(), name ='detail'),
    path('Constructor/',views.ConstructorIndexView.as_view(), name = 'constructor'),
    path('Category/create/',views.CategoryCreateview.as_view(), name = 'createcategory'),
    path('Good/create',views.GoodCreateview.as_view(), name = 'creategood'),
    path('category/delete',views.CategoryDeleteView.as_view(), name ='category_delete'),
    path('updategood<int:good>',views.GoodUpdateView.as_view(), name ='update_good'),
    path('good/delete',views.GoodDeleteView.as_view(), name ='good_delete'),
    
] 

constructor_site/figma/models.py
from django.db import models

# Base mixin
class BaseMixin(models.Model):
    title = models.CharField(max_length=30)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


# список категории
class Category(BaseMixin):
    pass


# список товаров
class Good(BaseMixin):
    price = models.DecimalField(max_digits=5, decimal_places=2)
    top = models.BooleanField(default=False)
    photo = models.ImageField(upload_to="images/", null=True, blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
    description = models.TextField(max_length=30, default='Описание')
    detail = models.TextField(max_length=30, default='Подробности')
    Shipping_Returns = models.TextField(max_length=30, default='Доставка и Возврат')			

constructor_site/figma/forms.py
from django import forms
from .models import Category
from .models import Good


class CategoryForm(forms.ModelForm):
        class Meta:
            model = Category 
            fields = ['title']


class GoodForm(forms.ModelForm):
        class Meta:
            model = Good 
            fields = ['title','price','top','category','photo',]

constructor_site/figma/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateResponseMixin, View
from .models import Good, Category
from.forms import CategoryForm, GoodForm


#
class ClientIndexView(TemplateResponseMixin,View):
    template_name = 'figma/client-site/index.html'

    def get (self, request, *args, **kwargs):
        user_site = self.kwargs.get('user_site', None)
        category = self.kwargs.get('category', None)
        categories = Category.objects.all()
        goods = Good.objects.filter(top=True)
        if category:
            goods = goods.filter(category=category)
        return self.render_to_response({
            'categories': categories, 'goods': goods, 'user_site': user_site})


class ClientDetailView(TemplateResponseMixin,View):
    template_name = 'figma/client-site/detail_photo.html'
    
    def get (self, request, good=None, user_site=None):
        good = Good.objects.get(id=good)
        goods = Good.objects.all()
        return self.render_to_response({'good': good, 
            'user_site': user_site, 'goods': goods,})


class ConstructorIndexView(TemplateResponseMixin,View):
    template_name = 'figma/constructor-site/index.html'
    
    def get (self, request, user_site=None):
        categories = Category.objects.all()
        goods = Good.objects.filter(top=True)
        category_form = CategoryForm()
        good_form = GoodForm()
        return self.render_to_response({'user_site': user_site, 
            'category_form':category_form, 'good_form':good_form,
            'categories':categories, 'goods': goods})


class GoodCreateview(View):

    def get(self, request, user_site=None):
       user_site_base = UserSite.objects.get(url_address=user_site)
       good_obj = Good.objects.get(id=28)
       good_obj.pk = None
       good_obj.user_site = user_site_base
       good_obj.save()
       return redirect('figma:constructor', user_site=user_site)
        

class GoodCreateview(View):

    def post (self, request, user_site=None):
        good_form = GoodForm(request.POST, request.FILES)
        if good_form.is_valid():
            good_form.save()
            return redirect('figma:constructor', user_site=user_site)


class CategoryDeleteView(View):

    def post (self, request, user_site):
        category_id = request.POST.get('category_id')
        Category.objects.get(id=category_id).delete()
        return HttpResponse({'durys'})


class GoodDeleteView(View):

    def get (self, request, user_site): 
        good_id = request.GET.get('good_id')
        Good.objects.get(id=good_id).delete()
        return HttpResponse({'status': False, 'error': 'ADSD'})


class GoodUpdateView(View):
 
    def dispatch(self, request, good, user_site):
        self.good = Good.objects.get(id=good)
        return super().dispatch(request, good, user_site)

    def get (self, request, good, user_site):
        good_form = GoodForm(instance=self.good)
        return render(request, 'figma/constructor-site/update.html',{
            'good_form':good_form, 'good': self.good, 
            'user_site':user_site})  

    def post (self, request, good, user_site):
        good_form = GoodForm(request.POST,request.FILES, instance=self.good)
        if good_form.is_valid():
            good_form.save()
            return redirect('figma:constructor', user_site=user_site)

constructor_site/templates/figma/client-site/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <title>Divisima</title>
  <meta name="description" content=" Divisima | eCommerce Template">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


	<meta name="keywords" content="divisima, eCommerce, creative, html">

	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/figma/bootstrap.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/font-awesome.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/flaticon.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/slicknav.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/jquery-ui.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/owl.carousel.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/animate.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/app.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/fonts.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/figma/style.css' %}"/>
	<title></title>
</head>
<body>
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 text-center text-lg-left">
						<!-- logo -->

							<img src="{% static 'figma/img/logo.png' %}" alt="">
						</a>
					</div>
					<!--<div class="col-xl-6 col-lg-5">
						<form class="header-search-form">
							<input type="text" placeholder="Поиск товара ....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>-->
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="#">Главная страница</a></li>
					<li><a href="#">Для парня / отца</a></li>
					<li><a href="#">Для девушки / мамы</a></li>
					<li><a href="#">Для новорожденного</a></li>


					<!--li><a href="#">Shoes</a>
						<ul class="sub-menu">
							<li><a href="#">Sneakers</a></li>
							<li><a href="#">Sandals</a></li>
							<li><a href="#">Formal Shoes</a></li>
							<li><a href="#">Boots</a></li>
							<li><a href="#">Flip Flops</a></li>
						</ul>
					</li-->
					<!--li><a href="#">Pages</a>
						<ul class="sub-menu">
							<li><a href="./product.html">Product Page</a></li>
							<li><a href="./category.html">Category Page</a></li>
							<li><a href="./categorynew.html">Cart Page</a></li>
							<li><a href="./checkout.html">Checkout Page</a></li>
							<li><a href="./contact.html">Contact Page</a></li>
						</ul>
					</li>
					<li><a href="#">Blog</a></li-->
				</ul>
			</div>
		</nav>
	</header>


	{% block content %}	{% endblock %}

	<section class="footer-section">
		<div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
					<a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
					<a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
					<a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
				</div>
			</div>
		</div>
	</section>

  <script src="{% static 'js/figma/app.js' %}"></script>
  <script src="{% static 'js/figma/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/figma/hoverable-collapse.js' %}"></script> 
  <script src="{% static 'js/figma/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery.slicknav.min.js' %}"></script>
  <script src="{% static 'js/figma/jquery.zoom.min.js' %}"></script>
  <script src="{% static 'js/figma/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/figma/main.js' %}"></script>
  <script src="{% static 'js/figma/map.js' %}"></script>
  <script src="{% static 'js/figma/off-canvas.js' %}"></script>
  <script src="{% static 'js/figma/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/figma/Preview.js' %}"></script>
  <script src="{% static 'js/figma/template.js' %}"></script>
  <script src="{% static 'js/js.cookie.min.js' %}"></script>


</body>
</html>

constructor_site/templates/figma/client-site/detail_photo.html
{% extends 'figma/client-site/base.html' %}
 {% block content %}

<body class="sidebar-fixed">

  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    
  <!-- main-panel-->
      <div class="main-panel">
        <div class="content-wrapper">
          <!-- Header section -->
           
            <!-- Header section end -->
              <!-- product section -->
            <form action="" method="POST" enctype="multipart/form-data">
              <section class="product-section">
                <div class="container">
                  <!-- <input type="submit" class="btn btn-sm btn-primary" name="" value="Сохранить"> -->
                  <div class="row">
                    <div class="col-lg-6">
                      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel"  data-interval="false" style="">
                        <div class="carousel-inner">
                           <div class="carousel-item active">
                            <div id="image-preview-extra" >
                              <img src="{{good.photo.url}}">
                             
                              <div class="box">
                               
                              </div>

                            </div>
                          </div>

                          <div class="carousel-item">
                            <div id="image-preview-extra1" class="carusel-wh">
                              <div class="box">

                              </div>
                            </div>
                          </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                          <span class="fa fa-chevron-left icon-slaider"></span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                          <span class="fa fa-chevron-right icon-slaider"></span>
                        </a>
                      </div>
                    </div>
                    <div class="col-lg-6 product-details">
                      <div class="pi-text">  
                        <h2 class="p-title" style="font-weight: 400;">{{good.title}}</h2>
                        <h3 class="p-price" style="font-weight: 600;">
                          {{good.price}} тг
              <del style="color: #de0047;font-weight: 600;margin-left: 5px;font-size: 18px;">
                20000 тг
              </del>
                      </h3>
                   


                      </h3><br>
                      <div class="input-text-modal">
                        <div class="form-group">
                            <label for="validationTooltipUsername" id="css_cs_cursor" style="font-size: 22px;">Пред. осмотр: </label>

                            <span id="preview-content" class="font-anastasiaScriptC color-gold font-style"></span>
                            <br>

                            <input type="text" id="preview-text" class="form-field form-contact"  placeholder="Введите имя или текст ...">
<div class="form-group">
                <label for="exampleFormControlSelect1" id="css_cs_cursor" style="font-size: 22px; ">Выберите материал:</label>
                <select class="form-control form-contact">
                  <option value="Серебро">Серебро</option>
                  <option value="Подзолото">Подзолото</option>
                  <option value="Золото">Золото</option>
                </select>
              </div>
                          <div class="form-group">
                           <a href="" class="site-btn" data-toggle="modal" data-target="#exampleModal">Заказать</a>

                          </div>
                      </div>

 <div id="accordion" class="accordion-area">
            <div class="panel">
              <div class="panel-header" id="headingOne">
                <button style="min-height: 50px;" class="panel-link active" data-toggle="collapse" data-target="#collapse1" aria-expanded="true" aria-controls="collapse1">Описание</button>
              </div>
              <div id="collapse1" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="panel-body">
                  {{good_form.description}}
                  jjjj
                  <p class="p-text"></p>
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-header" id="headingTwo">
                <button class="panel-link" data-toggle="collapse" data-target="#collapse2" aria-expanded="false" aria-controls="collapse2">Подробности </button>
              </div>
              <div id="collapse2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="panel-body">
                     {{good_form.detail}}
                  <p>Цвет <output class="pull-right">Розовое Золото</output> </p>
                  <p>Материал <output class="pull-right">Серебряный</output> </p>
                  <p>Вес <output class="pull-right">2,36 Г</output> </p>
                  <p>Рост <output class="pull-right">8-10мм</output> </p>
                  <p>Толщина <output class="pull-right">1мм</output> </p>
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-header" id="headingThree">
                <button class="panel-link" data-toggle="collapse" data-target="#collapse3" aria-expanded="false" aria-controls="collapse3">доставка и возврат</button>
              </div>
              <div id="collapse3" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="panel-body">
                     {{good_form.Shipping_Returns}}
                  <p>Вы можете выбрать способ доставки при оформлении заказа</p>
                  <p>Доставка в среднем : <span>3 - 4 дня</span></p>
                  <p>Сертификат качества на 3 года.  За это время мы вам, совершенно БЕСПЛАТНО: почистим, отремантируем</p>
                </div>
              </div>
            </div>
          </div>


                  </div>

                </div>
              </section>
              
                </div>
              </div>
              <!-- Modal -->
            </form>
            <!-- RELATED PRODUCTS section -->
            <!-- Footer section -->
            
            <!-- Footer section end -->
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- main-panel ends -->
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- base:js -->
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="js/figma/off-canvas.js"></script>
  <script src="js/figma/hoverable-collapse.js"></script>
  <script src="js/figma/template.js"></script>
</body>

{% endblock %}

{% block modal %}
<div class="modal" id="exampleModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Заказать</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form action="{% url 'figma:createcategory' user_site %}" method="post">
          {% csrf_token %}
      <p>Введите название категории</p>
      {{category_form.title}}
          <input type="submit"  value="save">
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

{% endblock %}

constructor_site/templates/figma/client-site/detail_text.html
{% extends 'figma/client-site/detail_photo.html' %}
 {% block content %}

 
{% endblock %}

constructor_site/templates/figma/client-site/index.html
{% extends 'figma/client-site/base.html' %}
{% block content %}
{% load static %}
<section class="hero-section">
<div class="hero-slider owl-carousel">
<div class="hs-item set-bg" data-setbg="">
<div class="container">
<div class="row">
	<div class="col-xl-6 col-lg-7 text-white">
		<span>ИМЕННЫЕ КУЛОНЫ МЕЧТЫ</span>
		<p>
			Представьте, что вы имеете единственный на свете кулон, который готовили только для тебя...✨</br>
			Вот это ДА! 🤭
		</p>
	</div>
</div>
<!--div class="offer-card text-white">
	<span>от</span>
	<h2>5000 тг</h2>
	<p>Купить сейчас</p>
</div-->
</div>
</div>
<div class="hs-item set-bg" data-setbg="{% static 'figma/img/02_8.jpg' %}">
<div class="container">
<div class="row">
	<div class="col-xl-6 col-lg-7 text-white">
		<span>🎁Нәзік жандыларға ең қатты ұнайтын сыйлық қандай екенін білесіз бе?</span>
		<p>Ең үздік шеберлердің қолынан шыққан алқамыз ешкімде жоқ, ерекше сыйлық болатынына сөз береміз👌🏻 </p>
	</div>
</div>
<!--div class="offer-card text-white">
	<span>from</span>
	<h2>$29</h2>
	<p>SHOP NOW</p>
</div-->
</div>
</div>
</div>
<div class="container">
<div class="slide-num-holder" id="snh-1"></div>
</div>
</section>
<section class="category-section spad">
<div class="container">
<div class="row">
<div class="col-lg-3 order-1 order-lg-1">
<div class="filter-widget">
<h2 class="fw-title">Категории</h2>
<ul class="category-menu">
    {% for category in categories %}
<li>
  <a href="{% url 'figma:index' category=category.id user_site='kd'%}">{{category.title}}</a>
</li>
      {% endfor %}
</ul>
</div>
</div>
<div class="col-lg-9  order-2 order-lg-2 mb-5 mb-lg-0">
<div class="row">
<div class="col-lg-12">
<div class="text-center">
<h2 class="border-b">Топ продаж</h2>
</div>   
 </div>
{%for good in goods %}
<div class="col-lg-4 col-sm-6">

<div class="product-item">
<br>
<div class="pi-pic">
<div class="tag-sale" style="margin-top: 10px;">Акция</div> 
<br>


<div>

{% if good.photo %}

<a href="{% url 'figma:detail' good=good.id user_site='kd'%}">  
<img src="{{good.photo.url}}" style="width: 300px; height: 200px;"></a>

{% endif %}

   </div>

   </a>

<div class="pi-links">

   <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>

</div>
  </div>


<div class="pi-text">
<span class="span-tg" style="color:#e81150;font-weight: bold;">{{good.price}} тг
</span>
<del style="font-size: 13px;">20000 тг</del>
<p style="color:#9a9a9a;">{{good.title}}</p>


</div>
</div>
</div>
{% endfor %}
</div>
</div>
</div>
</div>
</section>

{% endblock %}