constructor_site/constructor_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('', include('management_site.urls', namespace='management_site')),
    path('figma/', include('figma.urls')),
    path('<str:user_site>/sale/clothes/', include('sale_clothes.urls')),
    path('crm/', include('mini_crm.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

constructor_site/figma/urls.py
from django.urls import path
from . import views

app_name = 'figma'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),
    path('<int:category>',views.ClientIndexView.as_view(), name ='index'),
    path('detail/<int:good>',views.ClientDetailView.as_view(), name ='detail'),
    path('Constructor/',views.ConstructorIndexView.as_view(), name = 'constructor'),
    path('Category/create/',views.CategoryCreateview.as_view(), name = 'createcategory'),
    path('Good/create',views.GoodCreateview.as_view(), name = 'creategood'),
    path('category/delete',views.CategoryDeleteView.as_view(), name ='category_delete'),
    path('updategood<int:good>',views.GoodUpdateView.as_view(), name ='update_good'),
    path('good/delete',views.GoodDeleteView.as_view(), name ='good_delete'),
    
] 

constructor_site/sale_clothes/urls.py
from django.urls import path
from . import views

app_name = 'clothes'
urlpatterns = [
    path('',views.ClientIndexView.as_view(), name ='index'),
    path('good/list/<int:category>/',views.GoodListView.as_view(), name ='good_list'),
    path('good/list/<int:category>/<int:subcategory>',views.GoodListView.as_view(), name ='good_list'),
    path('detail/<int:good>',views.DetailView.as_view(), name ='detail'),
    path('add/bag/<int:good>',views.AddBagView.as_view(), name ='add_bag'),
    path('creat/category',views.CategoryCreatView.as_view(), name ='category_creat'),
] 

constructor_site/templates/clothes/client-site/bag.html
{% extends 'clothes/client-site/base.html' %}
{% load static %}
{% block content %}
	{% for good in goods %}
		{good.title}
	{% endfor %}
{% endblock %}

constructor_site/templates/clothes/client-site/detail.html
{% extends 'clothes/client-site/base.html' %}
{% load static %}
{% load sale_tags %}
{% block content %}
	<section>
                <div class="container">
                    <div class="product-single">
                        <div class="row mb24 mb-xs-48">
                            <div class="col-md-5 col-sm-6">
                                <div class="image-slider slider-thumb-controls controls-inside">
                                    <span class="label">Sale</span>
                                    <ul class="slides">
                                    	{% if good.photo %}
                                        <li>
                                            <img alt="Image" src="{{good.photo.url}}" />
                                        </li>
                                        {% endif %}

                                        {% if good.photo2 %}
                                        <li>
                                            <img alt="Image" src="{{good.photo2.url}}" />
                                        </li>
                                        {% endif %}

                                        {% if good.photo3 %}
                                        <li>
                                            <img alt="Image" src="{{good.photo3.url}}" />
                                        </li>
                                        {% endif %}
                                        {% if good.photo4 %}
                                        <li>
                                            <img alt="Image" src="{{good.photo4.url}}" />
                                        </li>
                                        {% endif %}

                                    </ul>
                                </div>
                                <!--end of image slider-->
                            </div>
                            <div class="col-md-5 col-md-offset-1 col-sm-6">
                                <div class="description">
                                    <h4 class="uppercase">{{good.title}}</h4>
                                    <div class="mb32 mb-xs-24">
                                        <!--<span class="number price old-price">$</span>-->
                                        <span class="number price">${{good.price}}</span>
                                    </div>
                                    <p>
                                        {{good.description}}
                                    </p>
                                    <ul>
                                        <li>
                                            <strong>SKU:</strong> {{good.counter}}</li>
                                        <li>
                                            <strong>COLOURS:</strong>{{good.color}}</li>
                                        <li>
                                            <strong>SIZES:</strong> {{good.sizes}}</li>
                                    </ul>
                                </div>
                                <hr class="mb48 mb-xs-24">
                                <form class="add-to-cart">
                                    <input type="text" placeholder="QTY" />
                                    <input type="submit" value="Add To Cart" />
                                </form>
                            </div>
                        </div>
                        <!--end of row-->
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="tabbed-content text-tabs">
                                    <ul class="tabs">
                                        <li>
                                            <div class="tab-title">
                                                {% get_additional_data 'raitingtitle' as raitingtitle %}
                                                  <span id="raitingtitle">
                                                     {{raitingtitle.label|default:"--"}}
                                                  </span>
                                            </div>
                                            <div class="tab-content">
                                            {% for coment in coments %}
                                                <ul class="ratings">
                                                	
                                                    <li>
                                                        <div class="user">
                                                            <ul class="list-inline star-rating">
                                                                <li>
                                                                    <i class="ti-star"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="ti-star"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="ti-star"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="ti-star"></i>
                                                                </li>
                                                            </ul>
                                                            <span class="bold-h6">{{coment.name}}</span>
                                                            <span class="date number">{{coment.date}}</span>
                                                        </div>
                                                        <p>
                                                            {{coment.text}}
                                                        </p>
                                                    </li>
                                                </ul>
                                            {% endfor %}
                                                <!--end of ratings-->
                                                {% get_additional_data 'ostavitotzyf' as ostavitotzyf %}
                                                  <h6 class="uppercase" id="ostavitotzyf">
                                                     {{ostavitotzyf.label|default:"--"}}
                                                  </h6>
                                                <form class="ratings-form" action="" method="post">
                                                	{% csrf_token %}
                                                    <div class="overflow-hidden">
                                                        <span pattern="soin">{{coment_form.name}}</span>
                                                        {{coment_form.email}}
                                                    </div>
                                                    <!--
                                                    <div class="select-option">
                                                        <i class="ti-angle-down"></i>
                                                        <select>
                                                            <option selected value="Default">Select A Rating</option>
                                                            <option value="1">1 Star</option>
                                                            <option value="2">2 Stars</option>
                                                            <option value="3">3 Stars</option>
                                                            <option value="4">4 Stars</option>
                                                            <option value="5">5 Stars</option>
                                                        </select>
                                                    </div>-->
                                                    {{coment_form.text}}
                                                    <input type="submit" value="отправит коментарии" />
                                                </form>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <!--end of text tabs-->
                            </div>
                        </div>
                        <!--end of row-->
                    </div>
                    <!--end of product single-->
                </div>
                <!--end of container-->
            </section>
            <section class="pt0">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            {% get_additional_data 'textontopgood' as textontopgood %}
                              <h4 class="uppercase mb80 mb-xs-40" id="textontopgood">
                                 {{textontopgood.label|default:"--"}}
                              </h4>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                    	{% for good in goods %}
                        <div class="col-md-3 col-sm-4">
                        	
                            <div class="image-tile outer-title text-center">
                                <a href="{% url 'clothes:detail' good=good.id user_site='wedf' %}">
                                    <img alt="Pic" class="product-thumb" src="{{good.photo.url}}" />
                                </a>
                                <div class="title">
                                    <h5 class="mb0">
                                        <br />{{good.title}}</h5>
                                    <span class="display-block mb16">${{good.price}}</span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
{% endblock %}

constructor_site/templates/clothes/client-site/good_list.html
{% extends 'clothes/client-site/base.html' %}
{% load sale_tags %}
{% block content %}
<section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3">
                            
                            <!--end of row-->
                            <div class="row masonry">
                              {% for good in goods %}
                                <div class="col-md-4 col-sm-4 masonry-item col-xs-12">
                                    <div class="image-tile outer-title text-center">
                                        <a href="{% url 'clothes:detail' good=good.id user_site='wedf' %}">
                                            <img alt="Pic" class="product-thumb" src="{{good.photo.url}}" />
                                        </a>
                                        <div class="title">
                                            <h5 class="mb0">
                                                <br />{{good.title}}</h5>
                                            <span class="display-block mb16">${{good.price}}</span>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <!--end of row-->
                            <div class="text-center mt40">
                                <ul class="pagination">
                                    <li>
                                        <a href="#" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#">1</a>
                                    </li>
                                    <li>
                                        <a href="#">2</a>
                                    </li>
                                    <li>
                                        <a href="#">3</a>
                                    </li>
                                    <li>
                                        <a href="#">4</a>
                                    </li>
                                    <li>
                                        <a href="#">5</a>
                                    </li>
                                    <li>
                                        <a href="#" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!--end of nine col-->
                        <div class="col-md-3 col-md-pull-9 hidden-sm">
                            <div class="widget">
                                {% get_additional_data 'categorytitle' as categorytitle %}
                                  <h6 class="title" id="categorytitle">
                                     {{categorytitle.label|default:"--"}}
                                  </h6>
                                <hr>
                                <ul class="link-list">
                                  {% for undercategory in undercategories %}
                                    <li>
                                        {% if undercategory %}
                                        <a href="{% url 'clothes:good_list' category=category  subcategory=undercategory.id  user_site='wedf' %}">{{undercategory.title}}</a>
                                        {% else %}
                                        <a href="">no category</a>
                                        {% endif %}
                                    </li>
                                  {% endfor %}
                                </ul>
                            </div>
                            <!--end of widget-->
                            <div class="widget">
                                {% get_additional_data 'searchgoodtitle' as searchgoodtitle %}
                                  <h6 class="title" id="searchgoodtitle">
                                     {{searchgoodtitle.label|default:"--"}}
                                  </h6>
                                <hr>
                                <form>
                                    <input class="mb0" type="text" placeholder="Type Here" />
                                </form>
                            </div>
                            <!--end of widget-->
                            <div class="widget">
                                {% get_additional_data 'populargoodstitle' as populargoodstitle %}
                                  <h6 class="title" id="populargoodstitle">
                                     {{populargoodstitle.label|default:"--"}}
                                  </h6>
                                <hr>
                                <ul class="cart-overview">
                                    {% get_good_limit list_goods=list_goods limit=3 as goods_list %}
                                    {% for good in goods_list %}
                                    <li>
                                        <a href="#">
                                            {% if good.photo2 %}
                                            <img alt="Product" src="{{good.photo2.url}}" />
                                            <div class="description">
                                                <span class="product-title">{{good.title}}</span>
                                                <span class="price number">${{good.price}}</span>
                                            </div>
                                            {% endif %}
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <!--end of widget-->
                            <div class="widget">
                                {% get_additional_data 'aboutgoodtitle' as aboutgoodtitle %}
                                  <h6 class="title" id="aboutgoodtitle">
                                     {{aboutgoodtitle.label|default:"--"}}
                                  </h6>
                                <hr>
                                {% get_additional_data 'aboutgoodtext' as aboutgoodtext %}
                                  <p id="aboutgoodtext">
                                     {{aboutgoodtext.label|default:"--"}}
                                  </p>
                            </div>
                            <!--end of widget-->
                            
                            <!--end of widget-->
                        </div>
                        <!--end of sidebar-->
                    </div>
                    <!--end of container row-->
                </div>
                <!--end of container-->
            </section>
{% endblock %}